[workspace]
resolver = "3"
members = ["compact", "ingest", "integration", "otlp", "prism", "query", "schema", "store"]

[workspace.dependencies]
axum = "0.8"
chrono = "0.4.45"
clap = { version = "4", features = ["derive", "env"] }
datafusion = "54.1.0"
compact = { path = "compact" }
ingest = { path = "ingest" }
integration = { path = "integration" }
query = { path = "query" }
prism = { path = "prism" }
otlp = { path = "otlp" }
schema = { path = "schema" }
store = { path = "store" }
tokio = "1.53.1"
uuid = { version = "1.24.1", features = ["v7"] }
